### ISSUE TITLE
*.req files fail to install

### ISSUE THREAD

**Issue by kmpeters** [epics-modules/motor#138]
The ``motorApp/Db/*.req`` files fail to install when building against both base 3.14 and 3.15.  This doesn't break builds of motor or driver code, but it does break builds of example IOCs.

**Comment by timmmooney** [comment]
By the way, there's an intended way to override the .req files in synApps:  autosave has a request-file path, which we populate with commands like this:

set_requestfile_path("$(TOP)/iocBoot/$(IOC)", "")
set_requestfile_path("$(BUSY)", "busyApp/Db")
etc.

If you make your own copy of, say, motor_settings.req and put it in a directory that comes before the motor modules directory, autosave will use your copy.

Tim Mooney (mooney@anl.gov) (630)252-5417
Beamline Controls Group (www.aps.anl.gov)
Advanced Photon Source, Argonne National Lab

________________________________
