### ISSUE TITLE
devOmsCom.cc is not completely device independent

### ISSUE THREAD

**Issue by hjunkes** [epics-modules/motor#179]
In devOmsCom.cc the hard-coded driver table of the oms58 is used.
I don't understand the construct, but shouldn't e.g. when using a MAXv card,
the driver table of that card (MAVv_access) be accessed?

Line 247:
  if ((command == PRIMITIVE) && (mr->init != NULL) &&
        (strlen(mr->init) != 0))
    {
        extern struct driver_table oms58_access;
        /* Test for a "device directive" in the Initialization string. */
        if ((mr->init[0] == '@') && (trans->tabptr == &oms58_access))
        {
            char *end = strrchr(&mr->init[1], '@');
            if (end != NULL)
            {

**Comment by kmpeters** [comment]
Closing this issue in favor of the new one in motorOms.
