### ISSUE TITLE
<motor>/README looks out of place

### ISSUE THREAD

**Issue by prjemian** [epics-modules/motor#9]
This HTML page contains release notes and known problems for current development and past releases.  Shouldn't this go into the documentation subdirectory?

**Comment by kmpeters** [comment]
My understanding is that the <motor>/README contains details about changes to the motor module that only developers would care about.  The release notes HTML page contains a higher-level view of the same changes and is intended for users of the module.

**Comment by prjemian** [comment]
We should describe this clearly on the README.md page that appears on the GH repository landing page.

**Comment by kmpeters** [comment]
I added a note to the README in commit 497bdac0c9e6e5c9e7873157cdeb262ce15b3358 letting people know that the file won't be updated in the future.  This feels like a better place to document it than the motor module landing page; I'd rather not draw attention to a file that will not be maintained in the future.
