### ISSUE TITLE
Logic test for EPICS version in motor.h is incorrect

### ISSUE THREAD

**Issue by MarkRivers** [epics-modules/motor#90]
motor.h contains this:
```
/* Less than EPICS base version test.*/
#define LT_EPICSBASE(v,r,l) ((EPICS_VERSION<=(v)) && (EPICS_REVISION<=(r)) && (EPICS_MODIFICATION<(l)))
```
This logic is incorrect.

Consider the case where EPICS base is 1.0.1, i.e. EPICS_VERSION=1 EPICS_REVISION=0, EPICS_MODIFICATION=1.

Then LT_EPICSBASE(2, 0, 0) should be true.  But it will be false because EPICS_MODIFICATION=1 is not less than 0.

This should be changed to use the code that is in many other modules, for example sscan/sscanApp/src/recDynLink.c.

```
/* Less than EPICS base version test.*/
#ifndef EPICS_VERSION_INT
#define VERSION_INT(V,R,M,P) ( ((V)<<24) | ((R)<<16) | ((M)<<8) | (P))
#define EPICS_VERSION_INT VERSION_INT(EPICS_VERSION, EPICS_REVISION, EPICS_MODIFICATION, EPICS_PATCH_LEVEL)
#endif
#define LT_EPICSBASE(V,R,M,P) (EPICS_VERSION_INT < VERSION_INT((V),(R),(M),(P)))
```

**Comment by rsluiter** [comment]
Yes. That logic is wrong. Replaced it with the SSCAN's version. Tried to removed the EPICS_PATCH_LEVEL part, but EPICSbase 3.15 and above defines VERSION_INT, so I added EPICS_PATCH_LEVEL to the effected code instead here; https://github.com/epics-modules/motor/commit/c1c440764414627237580c2642bf5542aee623b2
Thanks.
